import {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {injuryTypes,commonInjuryFields,careFields,injuryDetails} from '../utils/injuryData';
import {indiaToday,isPast} from '../utils/safetyData';
import './SafetyRecords.css';
const API=process.env.REACT_APP_API_URL;
export default function InjuryIncidents({category}){
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[retry,setRetry]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[editor,setEditor]=useState(null),[draft,setDraft]=useState({}),[history,setHistory]=useState(null),[query,setQuery]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[month,setMonth]=useState(''),[status,setStatus]=useState(''),[all,setAll]=useState(false);const formRef=useRef(null);
 useEffect(()=>{const c=new AbortController();let live=true;setLoading(true);setLoadError('');(async()=>{try{const r=await fetch(API+'/injury-incidents',{signal:c.signal}),data=await r.json();if(!r.ok||!Array.isArray(data))throw Error(data.message||'Could not load incidents');if(live)setRows(data);}catch(e){if(live)setLoadError(e.message);}finally{if(live)setLoading(false);}})();return()=>{live=false;c.abort();};},[retry]);
 useEffect(()=>{if(editor)formRef.current?.scrollIntoView({block:'start'});},[editor]);
 const badDates=from&&to&&from>to,filtered=badDates?[]:rows.filter(r=>(all||r.category===category)&&(!month||(r.date||'').slice(0,7)===month)&&(!(from||to)||/^\d{4}-\d{2}-\d{2}/.test(r.date||''))&&(!from||r.date>=from)&&(!to||r.date.slice(0,10)<=to)&&(!status||r.actionStatus===status)&&(!query||injuryDetails(r).map(([,v])=>String(v)).join(' ').toLowerCase().includes(query.toLowerCase())));
 function start(action,row){setError('');setMessage('');setHistory(null);setDraft({...Object.fromEntries([...commonInjuryFields,...Object.values(careFields).flat()].map(([k])=>[k,''])),category,date:indiaToday(),...row,updatedBy:'',reason:'',reviewedBy:'',reviewConfirmed:false,closedDate:indiaToday(),closureNote:''});setEditor({action,row});}
 const change=(k,v)=>setDraft(p=>({...p,[k]:v}));
 async function save(e){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const r=await fetch(API+'/injury-incidents'+(editor.row?'/'+editor.row._id:''),{method:editor.row?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...draft,action:editor.action,version:editor.row?.incidentVersion})}),data=await r.json();if(!r.ok)throw Error(data.message||'Save failed');setRows(prev=>editor.row?prev.map(row=>row._id===data._id?data:row):[data,...prev]);setMessage(editor.action==='reclassify'?`Incident moved to ${data.category}. Same ID and history preserved.`:'Incident saved.');setEditor(null);setHistory(null);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function loadHistory(row){setHistory({id:row._id,loading:true});try{const r=await fetch(API+'/injury-incidents/'+row._id+'/history'),data=await r.json();if(!r.ok)throw Error(data.message||'History unavailable');setHistory({id:row._id,...data});}catch(e){setHistory({id:row._id,error:e.message});}}
 async function report(dataRows,single=false){setBusy(true);setError('');try{const {downloadSafetyReport}=await import('../utils/safetyReport');await downloadSafetyReport({kind:'injury',rows:dataRows,filters:single?{category:dataRows[0].category,query:'Individual incident'}:{from:month?month+'-01':from,to:month?'Month '+month:to,status,query,category:all?'FAC / MTI / LTI':category}});}catch(e){setError(e.message||'PDF failed');}finally{setBusy(false);}}
 function field([key,label,type,optional]){return <label key={key} className={type==='textarea'?'sr-wide':''}>{label}{optional?'':' *'}{type==='textarea'?<textarea required={!optional||(key==='lostDaysBasis'&&draft.daysLost!==''&&draft.daysLost!=null)} maxLength={key==='lostDaysBasis'?500:2000} value={draft[key]??''} onChange={e=>change(key,e.target.value)}/>:<input type={type} required={!optional} min={type==='number'?0:undefined} max={type==='number'?100000:['date','returnToWork','absenceStart'].includes(key)?indiaToday():undefined} maxLength={['injuredPerson','assignedTo','updatedBy','reviewedBy'].includes(key)?120:200} step={type==='number'?1:undefined} value={draft[key]??''} onChange={e=>change(key,e.target.value)}/>}</label>;}
 return <main className="sr-page sr-near"><Link to="/safety/lagging">← Lagging Indicators</Link><header className="sr-hero"><small>WIDER ELECTRICAL · INCIDENT RECORDS</small><h1>{category} Incident Register</h1><div className="sr-toolbar">{injuryTypes.map(t=><Link key={t} to={'/safety/lagging/'+t.toLowerCase()}>{t}</Link>)}<button disabled={busy||loading||!!loadError} onClick={()=>start('create')}>+ Add Incident</button><button disabled={busy} onClick={()=>{setEditor(null);setHistory(null);setRetry(n=>n+1);}}>↻ Refresh</button><button disabled={busy||loading||!!loadError||!!badDates} onClick={()=>report(filtered)}>↓ Download filtered report</button></div></header>
 {message&&<p className="sr-message" role="status">{message}</p>}{error&&<p className="sr-error" role="alert">{error}</p>}
 {editor&&<form ref={formRef} className="sr-form" onSubmit={save}><h2>{({create:'New incident',edit:'Edit incident',reclassify:'Change classification',close:'Close corrective actions',reopen:'Reopen corrective actions'})[editor.action]}</h2><fieldset disabled={busy}><div className="sr-fields">
 {['create','edit','reclassify'].includes(editor.action)&&<><label>Classification<select disabled={editor.action==='edit'} value={draft.category} onChange={e=>change('category',e.target.value)}>{injuryTypes.map(t=><option key={t}>{t}</option>)}</select></label>{[...commonInjuryFields,...careFields[draft.category]].map(field)}</>}
 {editor.action==='reclassify'&&<>{field(['reason','Classification change reason','textarea'])}{field(['reviewedBy','Safety reviewer name','text'])}<label className="sr-wide"><input style={{width:'auto',display:'inline-block',marginRight:8}} type="checkbox" required checked={draft.reviewConfirmed} onChange={e=>change('reviewConfirmed',e.target.checked)}/>This classification change has been reviewed by the named safety reviewer.</label></>}
 {editor.action==='close'&&<>{[['cause','Cause','textarea'],['correctiveAction','Corrective action','textarea'],['closureNote','Closure verification','textarea'],['closedDate','Closing date','date']].map(field)}</>}
 {editor.action==='reopen'&&field(['reason','Reason for reopening','textarea'])}{field(['updatedBy',editor.action==='close'?'Closed by':'Your name','text'])}</div>
 {draft.category==='LTI'&&<p className="sr-note">Enter verified lost days and the counting basis used by your plant. Dates do not automatically calculate lost days.</p>}<div className="sr-toolbar"><button>{busy?'Saving…':'Save'}</button><button type="button" onClick={()=>setEditor(null)}>Cancel</button></div></fieldset></form>}
 {loading?<p role="status">Loading incidents…</p>:loadError?<p role="alert" className="sr-error">{loadError}</p>:<><div className="sr-filters"><label>Search<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, location, ID or description"/></label><label>Month<input type="month" value={month} onChange={e=>{setMonth(e.target.value);setFrom('');setTo('');}}/></label><label>From<input type="date" value={from} onChange={e=>{setFrom(e.target.value);setMonth('');}}/></label><label>To<input type="date" value={to} onChange={e=>{setTo(e.target.value);setMonth('');}}/></label><label>Actions<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All</option><option>Open</option><option>Closed</option></select></label><label>Classification<select value={all?'all':'current'} onChange={e=>setAll(e.target.value==='all')}><option value="current">{category}</option><option value="all">All FAC / MTI / LTI</option></select></label><button onClick={()=>{setQuery('');setFrom('');setTo('');setMonth('');setStatus('');setAll(false);}}>Clear</button></div>{badDates&&<p role="alert">From date must not be after To date.</p>}
 <p className="sr-note">{filtered.length} records shown. Reports use current classification and the selected filters. Action closure is separate from treatment or return-to-work status. Reviewer names are recorded declarations; this page does not verify user roles.</p>
 <div className="sr-grid">{!filtered.length?<p>No matching incidents.</p>:filtered.map(row=><article className="sr-card" key={row._id}><div className="sr-card-top"><b>{row.category}</b><span>{row.date}</span><b>Actions: {row.actionStatus}</b>{row.actionStatus==='Open'&&isPast(row.targetDate)&&<b className="sr-overdue">Overdue</b>}{row.category==='LTI'&&row.absenceStart&&!row.returnToWork&&<b className="sr-badge">Ongoing absence</b>}</div><h2>{row.location||'Location not recorded'}</h2><dl>{injuryDetails(row).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{String(v===''?'Not recorded':v)}</dd></div>)}</dl><div className="sr-toolbar">{row.actionStatus==='Closed'?<button disabled={busy} onClick={()=>start('reopen',row)}>Reopen actions</button>:<><button disabled={busy} onClick={()=>start('edit',row)}>Edit</button><button disabled={busy} onClick={()=>start('reclassify',row)}>Change classification</button><button disabled={busy} onClick={()=>start('close',row)}>Close actions</button></>}<button disabled={busy} onClick={()=>loadHistory(row)}>History</button><button disabled={busy} onClick={()=>report([row],true)}>↓ Incident PDF</button></div>
 {history?.id===row._id&&<section className="sr-history"><h3>Incident history</h3>{history.loading?<p>Loading…</p>:history.error?<p role="alert">{history.error}</p>:<>{!(history.events||[]).length&&!(history.legacy||[]).length&&<p>No changes recorded yet.</p>}{[...(history.events||[])].reverse().map((event,i)=><details key={i}><summary>{event.action} · {event.by} · {new Date(event.at).toLocaleString()}</summary>{event.note&&<p>{event.note}</p>}{event.reviewer&&<p>Safety reviewer: {event.reviewer}</p>}{['before','after'].filter(k=>event[k]).map(k=><div key={k}><h4>{k==='before'?'Before':'Saved values'}</h4>{injuryDetails(event[k]).map(([label,v])=><p key={label}>{label}: {String(v)}</p>)}</div>)}</details>)}{(history.legacy||[]).map(h=><details key={h._id}><summary>Legacy edit · {h.updatedBy||'Not recorded'} · {new Date(h.updatedAt).toLocaleString()}</summary>{injuryDetails(h.oldData||{}).map(([k,v])=><p key={k}>{k}: {String(v)}</p>)}</details>)}</>}</section>}
 </article>)}</div></>}
 </main>;
}
