import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import MotorQrCard from '../components/MotorQrCard';
import {normalize,filterMotors} from '../utils/motorFilters';
const API=process.env.REACT_APP_API_URL;
export default function MotorQrDirectory(){const [motors,setMotors]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0),[query,setQuery]=useState(''),[plant,setPlant]=useState(''),[page,setPage]=useState(1),[busy,setBusy]=useState(false),[progress,setProgress]=useState('');
 useEffect(()=>{const c=new AbortController();let live=true;setLoading(true);setError('');(async()=>{try{const r=await fetch(API+'/motor-search',{signal:c.signal}),data=await r.json();if(!r.ok||!Array.isArray(data))throw Error('Could not load motor directory');if(live)setMotors(data);}catch(e){if(live)setError(e.message);}finally{if(live)setLoading(false);}})();return()=>{live=false;c.abort();};},[retry]);
 const filtered=filterMotors(motors,{query,plant}),pages=Math.max(1,Math.ceil(filtered.length/24)),current=Math.min(page,pages),visible=filtered.slice((current-1)*24,current*24);
 const plants=Array.from(new Map(motors.filter(m=>m.plant).map(m=>[normalize(m.plant),m.plant])).values()).sort();
 async function download(){setBusy(true);setError('');setProgress('Preparing labels…');try{const {downloadMotorQrPdf}=await import('../utils/motorQrPdf');await downloadMotorQrPdf(filtered,(n,total)=>setProgress(`Preparing ${n} / ${total} labels…`));setProgress('PDF downloaded. Print at 100% / actual size.');}catch(e){setError(e.message||'Download failed');setProgress('');}finally{setBusy(false);}}
 return <main className="mq-directory"><Link to="/motors/search">← Master</Link><header className="mq-hero"><h1>Motor QR Codes</h1><p>Scan a code to open its motor details. Download a QR image, a single label, or all filtered labels.</p><p>Label serial numbers reflect the download date; the QR opens the latest saved motor record.</p></header><div className="mq-filters"><label>Search<input type="search" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}} placeholder="Motor, serial, location…"/></label><label>Production line<select value={plant} onChange={e=>{setPlant(e.target.value);setPage(1);}}><option value="">All lines</option>{plants.map(p=><option key={p}>{p}</option>)}</select></label><button disabled={loading||busy} onClick={()=>setRetry(n=>n+1)}>Refresh</button><button disabled={loading||busy||!filtered.length} onClick={download}>↓ Download {filtered.length} QR Labels (PDF)</button></div>{error&&<p role="alert" className="mq-error">{error}</p>}{progress&&<p role="status">{progress}</p>}{loading?<p role="status">Loading motors…</p>:<><p>{filtered.length} motors · Page {current} of {pages}</p>{!filtered.length?<p>No matching motors.</p>:<div className="mq-grid">{visible.map(m=><MotorQrCard key={m._id} motor={m}/>)}</div>}<nav className="mq-pagination" aria-label="QR pages"><button disabled={current===1} onClick={()=>setPage(current-1)}>← Previous</button><span>{current} / {pages}</span><button disabled={current===pages} onClick={()=>setPage(current+1)}>Next →</button></nav></>}</main>;
}
