import {useCallback,useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {safetyConfig,safetySummary,safetyBuckets,safetyDetails,indiaToday,isPast,observationStatus} from '../utils/safetyData';
import './SafetyRecords.css';
const API=process.env.REACT_APP_API_URL,states=['Reported','Under Review','Action Pending','Closed'];
const blankObservation=()=>({description:'',priority:'Medium',assignedTo:'',targetDate:indiaToday()});
const formatDate=d=>d?new Date(d).toLocaleString('en-GB'):'Not recorded';
export default function SafetyRecords({kind}){
 const config=safetyConfig[kind],formRef=useRef(null);
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[refresh,setRefresh]=useState(0),[editor,setEditor]=useState(null),[draft,setDraft]=useState({}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[history,setHistory]=useState(null),[linkDraft,setLinkDraft]=useState(null),[query,setQuery]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[status,setStatus]=useState('');
 const fetchRows=useCallback(async(signal)=>{const r=await fetch(`${API}/safety-workflow/${kind}`,{signal});const data=await r.json();if(!r.ok||!Array.isArray(data))throw Error(data.message||'Could not load records');return data;},[kind]);
 useEffect(()=>{const c=new AbortController();let live=true;setLoading(true);setLoadError('');fetchRows(c.signal).then(data=>{if(live)setRows(data);}).catch(e=>{if(live)setLoadError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;c.abort();};},[fetchRows,refresh]);
 useEffect(()=>{if(editor)formRef.current?.scrollIntoView({behavior:'auto',block:'start'});},[editor]);
 function start(row){setHistory(null);setLinkDraft(null);setError('');setMessage('');setDraft({...Object.fromEntries(config.fields.map(([k])=>[k,''])),date:indiaToday(),durationHours:'1',numberOfPeople:'',caseStatus:'Reported',...row,observationItems:row?(row.observationItems?.length?row.observationItems.map(o=>({...o})):[{...blankObservation(),description:typeof row.observations==='string'?row.observations:''}]):[blankObservation()],updatedBy:'',closedDate:indiaToday(),closureNote:''});setEditor(row||{});}
 async function save(e){e.preventDefault();if(busy)return;setBusy(true);setError('');setMessage('');try{const r=await fetch(`${API}/safety-workflow/${kind}${editor._id?'/'+editor._id:''}`,{method:editor._id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...draft,version:editor.recordVersion})});const data=await r.json();if(!r.ok)throw Error(data.message||'Save failed');setRows(prev=>editor._id?prev.map(row=>row._id===data._id?data:row):[data,...prev]);setEditor(null);setHistory(null);setMessage('Record saved. Its change history is available below.');try{setRows(await fetchRows());}catch{setError('Saved successfully, but linked status refresh failed. Refresh before relying on observation counts.');}}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function openHistory(row){setHistory({id:row._id,loading:true});try{const r=await fetch(`${API}/safety-workflow/${kind}/${row._id}/history`);const data=await r.json();if(!r.ok)throw Error(data.message||'History unavailable');setHistory({id:row._id,...data});}catch(e){setHistory({id:row._id,error:e.message});}}
 async function linkIssue(e){e.preventDefault();if(busy)return;setBusy(true);setError('');setMessage('');try{const r=await fetch(`${API}/safety-workflow/walk/${linkDraft.row._id}/observations/${linkDraft.observation.id}/link`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({updatedBy:linkDraft.by,version:linkDraft.row.recordVersion})});const data=await r.json();if(!r.ok)throw Error(data.message||'Could not link issue');setLinkDraft(null);setHistory(null);setMessage('Observation linked to Unsafe Raised. Close or reopen it from Unsafe Issues.');try{setRows(await fetchRows());}catch{setError('Issue linked, but status refresh failed. Refresh to see the updated link.');}}catch(e){setError(e.message);}finally{setBusy(false);}}
 const dateError=from&&to&&from>to;
 const filtered=dateError?[]:rows.filter(r=>(!(from||to)||/^\d{4}-\d{2}-\d{2}/.test(r.date||''))&&(!from||(r.date||'')>=from)&&(!to||(r.date||'').slice(0,10)<=to)&&(!status||(r.caseStatus||'Reported')===status)&&(!query||safetyDetails(kind,r).map(([k,v])=>String(v)).join(' ').toLowerCase().includes(query.toLowerCase())));
 const stats=safetySummary(kind,filtered),buckets=safetyBuckets(kind,filtered),max=Math.max(1,...buckets.map(b=>b[1]));
 async function download(){setBusy(true);setError('');try{const {downloadSafetyReport}=await import('../utils/safetyReport');await downloadSafetyReport({kind,rows:filtered,filters:{query,from,to,status}});}catch(e){setError(e.message||'PDF download failed');}finally{setBusy(false);}}
 function change(key,value){setDraft(prev=>({...prev,[key]:value}));}
 function obsChange(index,key,value){setDraft(prev=>({...prev,observationItems:prev.observationItems.map((o,i)=>i===index?{...o,[key]:value}:o)}));}
 return <main className={'sr-page sr-'+kind}><Link to="/safety/leading">← Leading Indicators</Link><header className="sr-hero"><small>WIDER ELECTRICAL · SAFETY RECORDS</small><h1>{config.title}</h1><div className="sr-toolbar"><button disabled={busy||loading||!!loadError} onClick={()=>start()}>+ Add {kind==='training'?'Training':kind==='walk'?'Safety Walk':'Incident'}</button><button disabled={busy} onClick={()=>{setEditor(null);setHistory(null);setLinkDraft(null);setRefresh(n=>n+1);}}>↻ Refresh</button><button disabled={busy||loading||!!loadError||!!dateError} onClick={download}>↓ Download PDF</button>{kind==='walk'&&<Link to="/safety/lagging/unsaferaised">Unsafe Issues ↗</Link>}</div></header>
 {error&&<p className="sr-error" role="alert">{error}</p>}{message&&<p className="sr-message" role="status">{message}</p>}
 {editor&&<form ref={formRef} className="sr-form" onSubmit={save}><h2>{editor._id?'Edit record':'New record'}</h2><fieldset disabled={busy}><div className="sr-fields">{config.fields.map(([key,label,type,optional])=><label className={type==='textarea'?'sr-wide':''} key={key}>{label}{optional?' (optional until Action Pending)':' *'}{type==='textarea'?<textarea required={!optional} maxLength={2000} value={draft[key]||''} onChange={e=>change(key,e.target.value)}/>:<input required={!optional} type={type} maxLength={key==='topic'?300:key==='location'||key==='area'?200:120} min={type==='number'?key==='durationHours'?'0.01':'0':undefined} max={type==='number'?key==='durationHours'?'24':'100000':undefined} step={key==='durationHours'?'any':type==='number'?'1':undefined} value={draft[key]??''} onChange={e=>change(key,e.target.value)}/>}</label>)}
 {kind==='near'&&<><label>Status<select value={draft.caseStatus||'Reported'} onChange={e=>change('caseStatus',e.target.value)}>{states.filter((s,i)=>s===(editor.caseStatus||'Reported')||(editor._id&&i===states.indexOf(editor.caseStatus||'Reported')+1)).map(s=><option key={s}>{s}</option>)}</select></label>{draft.caseStatus==='Closed'&&<><label>Closing date<input type="date" required min={draft.date} max={indiaToday()} value={draft.closedDate} onChange={e=>change('closedDate',e.target.value)}/></label><label className="sr-wide">Closure verification<textarea required maxLength={2000} value={draft.closureNote} onChange={e=>change('closureNote',e.target.value)}/></label></>}</>}
 <label>Your name *<input required maxLength={120} value={draft.updatedBy} onChange={e=>change('updatedBy',e.target.value)}/></label></div>
 {kind==='walk'&&<div className="sr-observations"><h3>Observations</h3>{draft.observationItems.map((o,i)=><div className="sr-observation" key={o.id||i}><strong>Observation {i+1}</strong>{o.unsafeIssueId?<p>Linked issue: edit its priority, assignment and target date in <Link to="/safety/lagging/unsaferaised">Unsafe Issues</Link>.</p>:null}<div className="sr-fields"><label className="sr-wide">Observation<textarea required disabled={!!o.unsafeIssueId} maxLength={2000} value={o.description} onChange={e=>obsChange(i,'description',e.target.value)}/></label><label>Priority<select disabled={!!o.unsafeIssueId} value={o.priority} onChange={e=>obsChange(i,'priority',e.target.value)}>{['High','Medium','Low'].map(p=><option key={p}>{p}</option>)}</select></label><label>Responsible person<input required disabled={!!o.unsafeIssueId} maxLength={120} value={o.assignedTo} onChange={e=>obsChange(i,'assignedTo',e.target.value)}/></label><label>Target date<input required disabled={!!o.unsafeIssueId} type="date" min={draft.date} value={o.targetDate} onChange={e=>obsChange(i,'targetDate',e.target.value)}/></label></div>{!o.unsafeIssueId&&draft.observationItems.length>1&&<button type="button" onClick={()=>change('observationItems',draft.observationItems.filter((_,n)=>n!==i))}>Remove observation</button>}</div>)}<button type="button" disabled={draft.observationItems.length>=50} onClick={()=>change('observationItems',[...draft.observationItems,blankObservation()])}>+ Add observation</button></div>}
 <div className="sr-toolbar"><button>{busy?'Saving…':'Save record'}</button><button type="button" onClick={()=>setEditor(null)}>Cancel</button></div></fieldset></form>}
 {linkDraft&&<form className="sr-form" onSubmit={linkIssue}><h2>Create linked Unsafe Issue</h2><p>{linkDraft.observation.description}</p><label>Your name<input required maxLength={120} disabled={busy} value={linkDraft.by} onChange={e=>setLinkDraft({...linkDraft,by:e.target.value})}/></label><div className="sr-toolbar"><button disabled={busy}>Create Unsafe Issue</button><button disabled={busy} type="button" onClick={()=>setLinkDraft(null)}>Cancel</button></div></form>}
 {loading?<p role="status">Loading records…</p>:loadError?<p className="sr-error" role="alert">{loadError}</p>:<><div className="sr-filters"><label>Search<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Topic, area, name or description"/></label><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label>{kind==='near'&&<label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All</option>{states.map(s=><option key={s}>{s}</option>)}</select></label>}<button onClick={()=>{setQuery('');setFrom('');setTo('');setStatus('');}}>Clear</button></div>{dateError&&<p role="alert">From date must not be after To date.</p>}
 <div className="sr-stats">{stats.map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div><p className="sr-note">Showing {filtered.length} of {rows.length} records. Summaries, chart and PDF follow these filters.{kind==='training'?' Participants count attendances, not unique people. Man-hours exclude missing duration/count.':kind==='walk'?' Legacy free-text observations are retained but excluded from observation counts. Linked statuses refresh when this page loads or you press Refresh.':''}</p>
 <section className="sr-chart"><h2>{kind==='near'?'Incidents by location':'Records by month'}</h2>{!buckets.length?<p>No records to chart.</p>:<div className="sr-chart-scroll">{buckets.map(([label,count],i)=><div className="sr-bar-row" key={label}><span>{label}</span><div><i style={{width:100*count/max+'%',background:['#22d3ee','#f472b6','#a78bfa','#fbbf24','#34d399'][i%5]}}/></div><strong>{count}</strong></div>)}</div>}</section>
 <div className="sr-grid">{!filtered.length?<p>No matching records.</p>:filtered.map(row=><article className="sr-card" key={row._id}><div className="sr-card-top"><span>{row.date||'Date not recorded'}</span>{kind==='near'&&<b>{row.caseStatus||'Reported'}</b>}{kind==='near'&&row.caseStatus!=='Closed'&&isPast(row.targetDate)&&<b className="sr-overdue">Overdue</b>}</div><h2>{row.topic||row.area||row.location||config.title}</h2><dl>{safetyDetails(kind,row).filter(([label])=>!label.startsWith('Observation ')).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{String(value===null||value===undefined||value===''?'Not recorded':value)}</dd></div>)}</dl>
 {kind==='walk'&&(row.observationItems||[]).map((o,i)=><section className="sr-observation" key={o.id}><h3>Observation {i+1} <span className="sr-badge">{observationStatus(o)}</span></h3><p>{o.description}</p><p>{o.linkedPriority||o.priority} · {o.linkedAssignedTo||o.assignedTo} · Target: {o.linkedTargetDate||o.targetDate}</p>{observationStatus(o)==='Open'&&isPast(o.linkedTargetDate||o.targetDate)&&<b className="sr-overdue">Overdue</b>}{o.unsafeIssueId?<p><Link to={observationStatus(o)==='Closed'?'/safety/leading/unsafeclosed':'/safety/lagging/unsaferaised'}>Open linked Unsafe Issue ↗</Link></p>:<button disabled={busy} onClick={()=>{setEditor(null);setError('');setLinkDraft({row,observation:o,by:''});window.scrollTo({top:0,behavior:'auto'});}}>Create Unsafe Issue</button>}</section>)}
 <div className="sr-toolbar"><button disabled={busy||(kind==='near'&&row.caseStatus==='Closed')} onClick={()=>start(row)}>Edit / Update</button><button disabled={busy} onClick={()=>openHistory(row)}>History</button></div>
 {history?.id===row._id&&<section className="sr-history"><h3>Change history</h3>{history.loading?<p>Loading…</p>:history.error?<p role="alert">{history.error}</p>:<>{!(history.events||[]).length&&!(history.legacy||[]).length&&<p>No recorded edits yet.</p>}{[...(history.events||[])].reverse().map((event,i)=><details key={i}><summary>{event.action} · {event.by} · {formatDate(event.at)}</summary>{event.unsafeIssueId&&<p>Linked issue: {event.unsafeIssueId}</p>}{event.before&&<><h4>Before</h4>{safetyDetails(kind,event.before).map(([k,v])=><p key={k}><b>{k}:</b> {String(v)}</p>)}</>}{event.after&&<><h4>Saved values</h4>{safetyDetails(kind,event.after).map(([k,v])=><p key={k}><b>{k}:</b> {String(v)}</p>)}</>}</details>)}{(history.legacy||[]).map(h=><details key={h._id}><summary>Legacy edit · {h.updatedBy||'Not recorded'} · {formatDate(h.updatedAt)}</summary>{safetyDetails(kind,h.oldData||{}).map(([k,v])=><p key={k}>{k}: {String(v)}</p>)}</details>)}</>}</section>}
 </article>)}</div></>}
 </main>;
}
