import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import './UnsafeIssues.css';
const API=process.env.REACT_APP_API_URL;
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});
const overdue=row=>row.workflowStatus==='Open'&&row.targetDate&&row.targetDate<today();
const stamp=value=>value?new Date(value).toLocaleString('en-GB'):'Not recorded';
const initial=()=>({date:today(),location:'',description:'',assignedTo:'',priority:'Medium',targetDate:today(),updatedBy:''});
export default function UnsafeIssues({view}){
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[active,setActive]=useState(null),[draft,setDraft]=useState(initial),[message,setMessage]=useState(''),[reload,setReload]=useState(0),[history,setHistory]=useState([]),[historyError,setHistoryError]=useState('');
 useEffect(()=>{const c=new AbortController();let live=true;setLoading(true);setError('');
 (async()=>{try{const r=await fetch(API+'/unsafe-issues',{signal:c.signal});if(!r.ok)throw Error('Could not load unsafe issues. Please retry.');const data=await r.json();if(!Array.isArray(data))throw Error('Invalid issue data');if(live)setRows(data);}catch(e){if(live)setError(e.message);}finally{if(live)setLoading(false);}})();
 (async()=>{try{const r=await fetch(API+'/safety-history',{signal:c.signal});if(!r.ok)throw Error();const data=await r.json();if(!Array.isArray(data))throw Error();if(live){setHistory(data);setHistoryError('');}}catch{if(live)setHistoryError('Older edit history could not load. Refresh to retry.');}})();return()=>{live=false;c.abort();};},[reload]);
 function start(action,row){setMessage('');setActive({action,row});setDraft(action==='create'?initial():{...initial(),...row,updatedBy:'',actionTaken:'',closedDate:today(),reason:''});}
 async function save(e){e.preventDefault();if(busy)return;setBusy(true);setMessage('');try{const create=active.action==='create',r=await fetch(API+'/unsafe-issues'+(create?'':'/'+active.row._id),{method:create?'POST':'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...draft,action:active.action,version:active.row?.workflowVersion})});const data=await r.json();if(!r.ok)throw Error(data.message||'Save failed');setRows(prev=>create?[data,...prev]:prev.map(row=>row._id===data._id?data:row));setMessage(active.action==='close'?'Issue moved to Closed.':active.action==='reopen'?'Issue moved back to Raised / Open.':'Issue saved.');setActive(null);}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 const opened=rows.filter(r=>r.workflowStatus==='Open'),closed=rows.filter(r=>r.workflowStatus==='Closed'),shown=view==='closed'?closed:opened;
 return <main className="ui-page"><Link to="/safety">← Safety Details</Link><header className="ui-hero"><small>WIDER ELECTRICAL · UNSAFE ACT / CONDITION</small><h1>{view==='closed'?'Closed Issues':'Raised / Open Issues'}</h1><p>Raise → assign → resolve → close. Every change stays with the same issue.</p><nav><Link aria-current={view==='raised'?'page':undefined} to="/safety/lagging/unsaferaised">Raised / Open</Link><Link aria-current={view==='closed'?'page':undefined} to="/safety/leading/unsafeclosed">Closed</Link><button disabled={busy||loading} onClick={()=>{setActive(null);setReload(n=>n+1);}}>↻ Refresh</button><button disabled={busy||loading||!!error} onClick={()=>start('create')}>+ Raise Issue</button></nav></header>
 {loading?<p role="status">Loading issues…</p>:error?<p role="alert">{error}</p>:<><div className="ui-stats">{[['Total Raised',rows.length],['Open',opened.length],['Closed',closed.length],['Overdue',opened.filter(overdue).length]].map(([label,n])=><div key={label}><small>{label}</small><strong>{n}</strong></div>)}</div><p className="ui-note">Total includes all recorded unsafe issues, including legacy Closed records. Overdue means an open issue is past its target date (India time).</p>
 {message&&<p className="ui-message" role="status">{message}</p>}
 {active&&<form className="ui-form" onSubmit={save}><h2>{({create:'Raise Issue',edit:'Edit Issue',close:'Close Issue',reopen:'Reopen Issue'})[active.action]}</h2><div className="ui-fields">
 {(active.action==='create'||active.action==='edit')&&<>{active.action==='create'&&<label>Raised date<input required type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label>}<label>Location<input required maxLength={200} value={draft.location} onChange={e=>setDraft({...draft,location:e.target.value})}/></label><label>Priority<select value={draft.priority||'Medium'} onChange={e=>setDraft({...draft,priority:e.target.value})}>{['High','Medium','Low'].map(v=><option key={v}>{v}</option>)}</select></label><label>Assigned to<input required maxLength={120} value={draft.assignedTo||''} onChange={e=>setDraft({...draft,assignedTo:e.target.value})}/></label><label>Target date<input required type="date" value={draft.targetDate||''} onChange={e=>setDraft({...draft,targetDate:e.target.value})}/></label><label className="ui-wide">Description<textarea required maxLength={2000} value={draft.description||''} onChange={e=>setDraft({...draft,description:e.target.value})}/></label></>}
 {active.action==='close'&&<><label>Closing date<input type="date" required max={today()} value={draft.closedDate} onChange={e=>setDraft({...draft,closedDate:e.target.value})}/></label><label className="ui-wide">Action taken / repair details<textarea required maxLength={2000} value={draft.actionTaken} onChange={e=>setDraft({...draft,actionTaken:e.target.value})}/></label></>}
 {active.action==='reopen'&&<label className="ui-wide">Reason for reopening<textarea required maxLength={2000} value={draft.reason} onChange={e=>setDraft({...draft,reason:e.target.value})}/></label>}
 <label>{active.action==='close'?'Closed by':'Your name'}<input required maxLength={120} value={draft.updatedBy} onChange={e=>setDraft({...draft,updatedBy:e.target.value})}/></label></div><button disabled={busy}>{busy?'Saving…':'Save'}</button><button type="button" disabled={busy} onClick={()=>setActive(null)}>Cancel</button></form>}
 <div className="ui-grid">{!shown.length?<p>No {view==='closed'?'closed':'open'} issues recorded.</p>:shown.map(row=><article className="ui-card" key={row._id}><div className="ui-badges"><span className={'ui-priority ui-'+(row.priority||'unknown').toLowerCase()}>{row.priority||'Priority not set'}</span><span>{row.workflowStatus}</span>{overdue(row)&&<span className="ui-overdue">Overdue</span>}</div><h2>{row.location||'Location not recorded'}</h2><p className="ui-description">{row.description||'Description not recorded'}</p><dl>{[['Raised date',row.date],['Reported by',row.reportedBy],['Assigned to',row.assignedTo],['Target date',row.targetDate]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'Not recorded'}</dd></div>)}</dl>
 {row.workflowStatus==='Closed'&&<div className="ui-repair"><strong>Closure details</strong><p>{row.actionTaken||'Action not recorded in legacy entry'}</p><small>{row.closedBy||'Name not recorded'} · {row.closedDate||'Date not recorded'}</small></div>}
 <div className="ui-actions">{row.workflowStatus==='Open'?<><button disabled={busy} onClick={()=>start('edit',row)}>Edit</button><button disabled={busy} onClick={()=>start('close',row)}>Mark Closed</button></>:<button disabled={busy} onClick={()=>start('reopen',row)}>Reopen</button>}</div>
 <details><summary>Issue history</summary><small>Issue ID: {row._id}</small>{historyError&&<p>{historyError}</p>}{!(row.workflowEvents||[]).length&&<p>Legacy record: workflow history starts with the next change.</p>}{[...(row.workflowEvents||[])].reverse().map((event,i)=><div className="ui-event" key={i}><strong>{event.action}</strong> · {event.by}<p>{stamp(event.at)}</p>{event.note&&<p>{event.note}</p>}{event.closedDate&&<p>Closing date: {event.closedDate}</p>}{event.action==='edit'&&['location','description','priority','assignedTo','targetDate'].filter(k=>event.before?.[k]!==event.after?.[k]).map(k=><p key={k}>{k}: {event.before?.[k]||'Not set'} → {event.after?.[k]||'Not set'}</p>)}</div>)}{history.filter(h=>String(h.safetyId)===String(row._id)).map(h=><div className="ui-event" key={h._id}><strong>Previous edit · {h.updatedBy||'Not recorded'}</strong><p>{stamp(h.updatedAt)}</p><p>{h.oldData?.description}</p><p>{h.oldData?.location}</p></div>)}</details>
 </article>)}</div></>}
 </main>;
}
