export const safetyConfig={
 training:{title:'Training',fields:[['date','Training date','date'],['topic','Topic','text'],['trainer','Trainer','text'],['location','Location','text'],['numberOfPeople','Participants','number'],['durationHours','Duration (hours)','number']]},
 walk:{title:'Safety Walk Reports',fields:[['date','Walk date','date'],['area','Area','text'],['conductedBy','Conducted by','text']]},
 near:{title:'Near Miss Incidents',fields:[['date','Incident date','date'],['time','Incident time (India)','time'],['location','Location','text'],['reportedBy','Reported by','text'],['description','What happened','textarea'],['potentialConsequence','Potential consequence','textarea'],['immediateAction','Immediate action','textarea'],['assignedTo','Responsible person','text'],['targetDate','Target date','date'],['cause','Cause','textarea',true],['correctiveAction','Corrective action','textarea',true]]}
};
export const indiaToday=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});
export const isPast=date=>/^\d{4}-\d{2}-\d{2}$/.test(date||'')&&date<indiaToday();
export const observationStatus=o=>o.unsafeIssueId?(o.linkedStatus||'Unavailable'):'Open';
const finite=value=>value!==null&&value!==undefined&&String(value).trim()!==''&&Number.isFinite(Number(value))&&Number(value)>=0;
export function safetySummary(kind,rows){
 if(kind==='training'){const known=rows.filter(r=>finite(r.numberOfPeople)&&finite(r.durationHours));return [['Sessions',rows.length],['Participants',rows.reduce((s,r)=>s+(finite(r.numberOfPeople)?Number(r.numberOfPeople):0),0)],['Training man-hours',Number(known.reduce((s,r)=>s+Number(r.numberOfPeople)*Number(r.durationHours),0).toFixed(2))],['Missing duration / count',rows.length-known.length]];}
 if(kind==='walk'){const obs=rows.flatMap(r=>r.observationItems||[]);return [['Walks',rows.length],['Open observations',obs.filter(o=>observationStatus(o)==='Open').length],['Closed observations',obs.filter(o=>observationStatus(o)==='Closed').length],['Overdue',obs.filter(o=>observationStatus(o)==='Open'&&isPast(o.linkedTargetDate||o.targetDate)).length]];}
 return [['Incidents',rows.length],['Action Pending',rows.filter(r=>r.caseStatus==='Action Pending').length],['Closed',rows.filter(r=>r.caseStatus==='Closed').length],['Overdue',rows.filter(r=>r.caseStatus!=='Closed'&&isPast(r.targetDate)).length]];
}
export function safetyBuckets(kind,rows){const groups=new Map();for(const r of rows){const key=kind==='near'?(String(r.location||'Not recorded').trim().toLowerCase()):/^\d{4}-\d{2}/.test(r.date||'')?r.date.slice(0,7):'Undated';groups.set(key,(groups.get(key)||0)+1);}return [...groups].sort((a,b)=>kind==='near'?b[1]-a[1]||a[0].localeCompare(b[0]):a[0].localeCompare(b[0]));}
export function safetyDetails(kind,row){const fields=safetyConfig[kind].fields.map(([k,label])=>[label,row[k]??'Not recorded']);if(kind==='near')fields.push(['Status',row.caseStatus||'Reported'],['Closure verification',row.closureNote||'Not recorded'],['Closed by',row.closedBy||'Not recorded'],['Closing date',row.closedDate||'Not recorded']);if(kind==='walk'){if(typeof row.observations==='string'&&row.observations)fields.push(['Legacy observation',row.observations]);for(const [i,o] of (row.observationItems||[]).entries())fields.push([`Observation ${i+1}`,`${o.description}\nPriority: ${o.linkedPriority||o.priority}\nAssigned: ${o.linkedAssignedTo||o.assignedTo}\nTarget: ${o.linkedTargetDate||o.targetDate}\nStatus: ${observationStatus(o)}${o.unsafeIssueId?'\nUnsafe issue: '+o.unsafeIssueId:''}${o.linkedAction?'\nAction: '+o.linkedAction:''}`]);}return fields;}
